{{ config(materialized='table') }}

select ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE
from BRAZILIAN_E_COMMERCE.CURATED_TABLES_RAW_DATA.OLIST_ORDER_PAYMENTS_DATASET
