{{ config(materialized='table') }}

select CUSTOMER_ID,
 CUSTOMER_ZIP_CODE_PREFIX,
 CUSTOMER_CITY,
 CUSTOMER_STATE

from BRAZILIAN_E_COMMERCE.CURATED_TABLES_RAW_DATA.OLIST_CUSTOMERS_DATASET
where customer_unique_id='50e1b12ee1e2eab6157d9c0b035136af'